name: Docker + Ngrok (FastAPI)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Docker
        run: docker compose up -d

      - name: Install Ngrok
        run: |
          curl -sLo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip -o ngrok.zip
          sudo mv ngrok /usr/local/bin/
          sudo chmod +x /usr/local/bin/ngrok
      - name: Auth Ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start Ngrok tunnel (10 min)
        id: ngrok
        run: |
          ngrok http 8080 --log=stdout > ngrok.log &
          sleep 5
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | grep -oP '"public_url":"\Khttps://[^"]+')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "::notice title=Ngrok URL::$NGROK_URL"
          echo "Esperando 10 minutos..."
          sleep 600  # 10 minutos
          echo "Cerrando Ngrok y contenedor..."
          docker compose down
